### ISSUE TITLE
oauth2问题咨询

### ISSUE THREAD

**Issue by ccdf12** [lexburner/oauth2-demo#1]
你好！
我想问一下 这个配置应该是非常重要的 您能做一下解释吗？因为我在做例子的时候总是有验证问题,配置了这个之后就可以了
security:
  oauth2:
    resource:
      filter-order: 3

**Comment by lexburner** [comment]
@ccdf12 默认的oauth2过滤的级别非常的低，你可以理解成被spring security资深的过滤器拦截了，具体可以debug查看。没记错的话，spring security的过滤器级别是0，所以这里改成大于0就可以了。spring boot 1.4之后需要这个配置。

**Comment by ccdf12** [comment]
谢谢您的回复 
调试的时候大概也知道是过滤级别的问题。这个参数让我自己找我估计短时间是找不到的。
现在这块学习只能是自己摸索吗？有没有什么好点的资料或者数据推荐？

**Comment by lexburner** [comment]
@ccdf12 这个Order在oauth2的文档中提到了，文档里面强调了顺序的问题。除了在springboot的配置文件中修改，还可以对oauth2的资源服务器认证服务器配置@Order注解。关于如何学习，这一块资料的确比较少，国内很多博客一是比较老，二是过于简略，我一般的都是翻文档，debug看源码，分析接口。可以关注我的微信公众号：Kirito的技术分享

**Comment by ccdf12** [comment]
公众号已关注 当时有修改过资源服务器的order为6 但是没起作用 非常感谢您的帮助

**Comment by lexburner** [comment]
@ccdf12 
解决方案：
https://github.com/spring-projects/spring-security-oauth/issues/993
以及为什么spring1.5版本之后，将资源服务器的默认顺序放到了最后，参考这个讨论：
https://github.com/spring-projects/spring-boot/issues/5072#issuecomment-271510520
官方文档给出的更新提示以及解决方案：
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes#oauth-2-resource-filter
