### ISSUE TITLE
token存储问题

### ISSUE THREAD

**Issue by chuchushijingxi** [lexburner/oauth2-demo#10]
想请问一下您代码是如何将token一系列的参数存储在redis里面的呢？

**Comment by chuchushijingxi** [comment]
还想请问下如何不保存在redis里面。。

**Comment by chuchushijingxi** [comment]
谢谢了。我用JdbcTokenStore将生成的token存放在数据库里面了。感谢您的回复

**Comment by chuchushijingxi** [comment]
https://github.com/lexburner/oauth2-demo/blob/b036f4a5ec63cb5a6186172a3b57fef85fbe180b/client-credentials/src/main/java/moe/cnkirito/security/oauth2/config/OAuth2ServerConfig.java#L79-L84
请问下82行的scopes设置有什么用吗？可以对访问做权限处理吗

**Comment by chuchushijingxi** [comment]
`@Override
		public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
			//配置客户端,用于password认证
			clients.inMemory().withClient(clientID)
					.resourceIds(DEMO_RESOURCE_ID)
					.authorizedGrantTypes("password", "refresh_token")
					//all作用域 与 aLittle作用域
					.scopes("all", "aLittle")
					.authorities("oauth2")
					.secret(secret)
					.accessTokenValiditySeconds(5000);
		}
@Override
		public void configure(HttpSecurity http) throws Exception {
			http
					.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
					.and()
					.anonymous()
					.and()
					.authorizeRequests()
					//配置order访问控制，必须认证过后才可以访问
					.antMatchers("/order/**").access("#oauth2.hasScope('aLittle')||#oauth2.hasScope('all')")
					.antMatchers("/product/**").access("#oauth2.hasScope('all')");
		}`自己琢磨出来了。。

**Comment by chuchushijingxi** [comment]
> 
@Override
		public void configure(HttpSecurity http) throws Exception {
			http
					.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
					.and()
					.anonymous()
					.and()
					.authorizeRequests()
					//配置order访问控制，必须认证过后才可以访问
					.antMatchers("/order/**").access("#oauth2.hasScope('aLittle')||#oauth2.hasScope('all')")
					.antMatchers("/product/**").access("#oauth2.hasScope('all')");
		}
>

**Comment by chuchushijingxi** [comment]
_asd_

**Comment by chuchushijingxi** [comment]
研究出来了
@Override
		public void configure(ClientDetailsServiceConfigurer clients) throws Exception {
			//配置客户端,用于password认证
			clients.inMemory().withClient(clientID)
					.resourceIds(DEMO_RESOURCE_ID)
					.authorizedGrantTypes("password", "refresh_token")
					//all作用域 与 aLittle作用域
					.scopes("all", "aLittle")
					.authorities("oauth2")
					.secret(secret)
					.accessTokenValiditySeconds(5000);
		}

--------
@Override
		public void configure(HttpSecurity http) throws Exception {
			http
					.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.IF_REQUIRED)
					.and()
					.anonymous()
					.and()
					.authorizeRequests()
					//配置order访问控制，必须认证过后才可以访问
					.antMatchers("/order/**").access("#oauth2.hasScope('aLittle')||#oauth2.hasScope('all')")
					.antMatchers("/product/**").access("#oauth2.hasScope('all')");
		}

**Comment by chuchushijingxi** [comment]
感谢大佬提供的Demo

**Comment by lexburner** [comment]
scope 的用法还是挺复杂的，我也没太搞清，我所知的可以用来做 token 的权限（和user 的 role，authority有区别）。动态的scope没有使用场景，资源定好好，所有的scope都应该确定。
