### ISSUE TITLE
@Accessors(fluent = true, chain = true)这个配置用了，前台不能自动解析

### ISSUE THREAD

**Issue by shancg** [lexburner/oauth2-demo#16]
json对象到页面时，解析会出错，因为QQAccount的setter和getter会直接和属性名一样
页面解析json对象会用默认的setter和getter方法
怎么解决呢，我手动写的getter和setter，感觉不友好

**Comment by lexburner** [comment]
@Getter
@Setter
@Builder

lombok试试这个，@Accessors 的确兼容性不够好，一些框架解析 javabean 的默认格式是只认 get set 前缀的。
