### ISSUE TITLE
在请求token时，提示要登录，但是登录一直失败

### ISSUE THREAD

**Issue by gwxh** [lexburner/oauth2-demo#23]
我使用的spring boot 2.0.4，采用client模式进行认证，获取token出现basic验证框，自定义的账号无法登录
![image](https://user-images.githubusercontent.com/38777236/44253156-302aab00-a231-11e8-88b2-b31720cc56f0.png)
![image](https://user-images.githubusercontent.com/38777236/44253073-f35eb400-a230-11e8-8025-193e9f43b56d.png)
![image](https://user-images.githubusercontent.com/38777236/44253112-0ec9bf00-a231-11e8-9d78-4dbb7e3b2b59.png)

**Comment by jounghu** [comment]
我也遇到相同的问题

我采用authorization_code模式进行认证，第一步获取code，正常，通过code去获取token失败，同样如上诉，出现basic验证框

![pj 8pouxrvhh3xjx 12 hwy](https://user-images.githubusercontent.com/30997324/44253168-3882e600-a231-11e8-801e-3082bd1eb566.png)

application.properties

我明确禁用掉了 basic 验证

```property
security.basic.enabled=false
```

`WebSecurity.java`

```java
@Configuration
@EnableWebSecurity
@Order(2)
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    
    @Override
    protected void configure(AuthenticationManagerBuilder auth) throws Exception {
        auth.inMemoryAuthentication().withUser("hjs").password("123").roles("ADMIN");
    }

}
```

`ResourceServerCofig.java`

```java
@Configuration
@EnableResourceServer
@Order(3)
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {
    @Override
    public void configure(ResourceServerSecurityConfigurer resources) throws Exception {
        resources.resourceId("test").stateless(true);

    }

    @Override
    public void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests().antMatchers("/api/**").authenticated()
                .anyRequest().permitAll()
                .and()
                .csrf().disable();
    }

}
```

认证服务和资源服务在同一个项目中

**Comment by gwxh** [comment]
client模式，链接的空格没有去掉导致出现了basic验证框，已改掉。获取token，认证是成功了，但是返回了另一个错误。
![image](https://user-images.githubusercontent.com/38777236/44260055-e8fae500-a245-11e8-8577-b867321bb8a2.png)
没有报任何异常

**Comment by pioneer911** [comment]
@jounghu 新手想个问题，在这个demo中采用authorization_code模式进行认证时，如何把代码跑起来(尝试了多次，依旧没跑通)想请教一下是哪里的问题？

**Comment by jounghu** [comment]
@pioneer911  我用楼主的代码跑通了，自己写的代码怎么跑都有问题，不过你可以加我qq 1358199510 ，可以互相讨论一下

**Comment by Przeblysk** [comment]
@gwxh redis 服务启动下

**Comment by gwxh** [comment]
@Lxjazni7 谢谢了，好像就是因为这个问题。
