### ISSUE TITLE
{error:method_not_allowed,error_description:Request method 'GET' not supported}

### ISSUE THREAD

**Issue by luny52** [lexburner/oauth2-demo#3]
JDK 1.8 eclipse方式下run运行
GET方式无法访问oauth/token,需要用POST方式访问 用CURL工具: curl -X POST -d 'grant_type=client_credentials' "http://client_1:123456@localhost:8080/oauth/token"

而且还要正确连接redis,在配置文件application.yml里面配置正确的redis服务器地址,否则会报错Handling error: RedisConnectionFailureException, Cannot get Jedis connection;

**Comment by junyi5257** [comment]
1，Oauth2访问获取token， 默认就是要求使用post请求
2, 可以测试开发环境，可以使用内存模式存储token信息.

**Comment by xuanhuo** [comment]
我发现这个接口竟然要http://localhost:8080/oauth/token?username=user_1&password=123456&grant_type=password&scope=select&client_id=client_2&client_secret=123456 用post请求才能成功，但是所有的参数都附在了url上 不应该是get方法吗？

**Comment by lexburner** [comment]
默认配置只开启了POST请求，请求的参数可以是表单参数也可以是拼接在url后的参数。参数附在url上并不代表一定是get请求，这是http协议相关的内容。
如果希望允许get请求可以获取token，是有一个配置项的，具体看下文档吧。

**Comment by lexburner** [comment]
@luny52 @junyi5257 @xuanhuo 可以看下ClientCredentialsTokenEndpointFilter 类的源码
```
	@Override
	public Authentication attemptAuthentication(HttpServletRequest request, HttpServletResponse response)
			throws AuthenticationException, IOException, ServletException {

		if (allowOnlyPost && !"POST".equalsIgnoreCase(request.getMethod())) {
			throw new HttpRequestMethodNotSupportedException(request.getMethod(), new String[] { "POST" });
		}
```

里面默认配置了
```
private boolean allowOnlyPost = false;
```
可以通过
```
public void setAllowOnlyPost(boolean allowOnlyPost) {
		this.allowOnlyPost = allowOnlyPost;
	}
```
方法关闭。

**Comment by smallCC** [comment]
可以试一下在`AuthorizationServerConfiguration`配置:
```
@Override
public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
    endpoints
        .allowedTokenEndpointRequestMethods(HttpMethod.GET, HttpMethod.POST)
        ...
```

**Comment by xuanhuo** [comment]
那有没有什么办法，让url不带参数，而让参数放在body体内呢，感觉如果用password模式的话，password直接附在url有点不太好

**Comment by chenhaozx** [comment]
@luny52 我也是JDK8，直接用源码执行会报跟你一样的错误。
解决方法：
1. 不用redis，直接用内存来存token。
2. 按smallCC提供的方式，加配置，可以支持get,post.具体代码如下：

  public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
        	   endpoints
        	   .allowedTokenEndpointRequestMethods(HttpMethod.GET, HttpMethod.POST)
               .tokenStore(new InMemoryTokenStore())
               .authenticationManager(authenticationManager);
        }

**Comment by lexburner** [comment]
@smallCC @luny52 已添加，感谢。
