### ISSUE TITLE
认证验证失败

### ISSUE THREAD

**Issue by xiaofeig** [lexburner/oauth2-demo#4]
接口`/product/{id}`、`/order/{id}`在未提交认证信息的情况下均可正常访问。

**Comment by lexburner** [comment]
@xiaofeig {"error":"unauthorized","error_description":"Full authentication is required to access this resource"}
order
访问 order/{id} 路径应该会报这个错，我本地是没问题的

**Comment by junyi5257** [comment]
注意下，你的配置文件中，是不是没有这个：
`security:
  oauth2:
    resource:
      filter-order: 3`
我在使用的时候，没有这个配置，就导致可以直接访问。

**Comment by xiaofeig** [comment]
@junyi5257 谢谢，配置后可以了
