### ISSUE TITLE
提示 Full authentication is required to access this resource

### ISSUE THREAD

**Issue by just-moth** [lexburner/oauth2-demo#6]
把代码clone下来,jdk1.8运行
post和get访问/oauth/token都提示
![image](https://user-images.githubusercontent.com/36361486/38225070-b2cb6cba-3725-11e8-9ec1-43dfecef6ee1.png)

.antMatchers("/oauth/*").permitAll()这个配置没有起作用
用的postman接口测试

**Comment by lexburner** [comment]
你把完整的 http 请求发一下，有带上用户名和密码吗？

**Comment by lexburner** [comment]
![image](https://user-images.githubusercontent.com/11485990/38228335-6a0b44fe-3735-11e8-9558-4149728c5ea2.png)
我本地是没有问题的

**Comment by just-moth** [comment]
http://localhost:8080/oauth/token? username=user_1&password=123456& grant_type=password&scope=select& client_id=client_2&client_secret=123456

![image](https://user-images.githubusercontent.com/36361486/38228281-2011b11c-3735-11e8-93f0-9f727902fbe2.png)

我看了你博客的评论还有转载博客评论里都没有出现这个情况,但是我不知道哪里错了

**Comment by lexburner** [comment]
检查下 url，是不是 oauth/token? username=user_1 中间多了一个空格？

**Comment by lexburner** [comment]
检查下 url，是不是中间多了几个空格？

**Comment by just-moth** [comment]
空格原因 /尴尬  谢谢博主

**Comment by lexburner** [comment]
没事，没问题了的话关闭 issue 了
