### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by koudaiDemon** [lexburner/oauth2-demo#7]
你好，我在使用你的demo做练习的时候，发现@EnableResourceServer这个注解无法导包，我想是不是pom.xml中的依赖有问题。

**Comment by koudaiDemon** [comment]
我知道问题了，由于我直接使用的的是SpringBoot2.0所以和项目中的版本不同，现在我换回到了项目中的版本

**Comment by lexburner** [comment]
springboot2.0 自动配置的依赖很多都变了，谨慎升级。

**Comment by lexburner** [comment]
@koudaiDemon springboot2.0 的demo已经更新，使用springboot2.0的话可以查看新的demo。
