### ISSUE TITLE
是否支持 根据refresh_token获取新的access_token  

### ISSUE THREAD

**Issue by TnjK** [lexburner/oauth2-demo#9]
根据refresh_token获取新的access_token

POST
http://localhost/oauth/token?grant_type=refresh_token&refresh_token=c24a6143-97c8-4642-88b9-d5c5b902b487

DEMO默认是否支持该方式？

**Comment by lexburner** [comment]
默认情况下，client模式不支持刷新token，password模式支持刷新token

刷新token的端点为：

http://localhost:8080/oauth/token?grant_type=refresh_token&refresh_token=your_refresh_token&client_id=client_2&client_secret=123456
注意点：
```
        @Override
        public void configure(AuthorizationServerEndpointsConfigurer endpoints) throws Exception {
            endpoints
                    .tokenStore(new RedisTokenStore(redisConnectionFactory))
                    .authenticationManager(authenticationManager)
                    .userDetailsService(userDetailsService)
                    .allowedTokenEndpointRequestMethods(HttpMethod.GET, HttpMethod.POST);
            endpoints.reuseRefreshTokens(true);
        }
```
注意把 userDetailsService 配置到 AuthorizationServerEndpointsConfigurer 中

**Comment by lexburner** [comment]
已经更新到readme了，在最下面
